openapi: 3.1.0
info:
  description: The ConductorOne API is a HTTP API for managing ConductorOne resources.
  title: ConductorOne API
  version: 0.1.0-alpha
servers:
- description: The ConductorOne API server for the current tenant.
  url: "https://{tenantDomain}.logan.dev.ductone.com:2443"
  variables:
    tenantDomain:
      default: invalid-example
      description: The domain of the tenant to use for this request.
paths:
  /api/v1/app_resource/{app_id}/{app_resource_type_id}/{id}:
    get:
      description: Invokes the c1.api.app.v1.AppResourceService.Get method.
      operationId: c1.api.app.v1.AppResourceService.Get
      parameters:
      - explode: false
        in: path
        name: app_id
        required: true
        schema:
          description: The appId field.
        style: simple
      - explode: false
        in: path
        name: app_resource_type_id
        required: true
        schema:
          description: The appResourceTypeId field.
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          description: The id field.
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.app.v1.AppResourceServiceGetResponse'
          description: Successful response
  /api/v1/app_resource_type/{app_id}/{id}:
    get:
      description: Invokes the c1.api.app.v1.AppResourceTypeService.Get method.
      operationId: c1.api.app.v1.AppResourceTypeService.Get
      parameters:
      - explode: false
        in: path
        name: app_id
        required: true
        schema:
          description: The appId field.
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          description: The id field.
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.app.v1.AppResourceTypeServiceGetResponse'
          description: Successful response
  /api/v1/auth/introspect:
    get:
      description: Invokes the c1.api.auth.v1.Auth.Introspect method.
      operationId: c1.api.auth.v1.Auth.Introspect
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.auth.v1.IntrospectResponse'
          description: Successful response
  /api/v1/entitlement/search:
    post:
      description: Invokes the c1.api.requestcatalog.v2.RequestCatalogSearchService.SearchEntitlements
        method.
      operationId: c1.api.requestcatalog.v2.RequestCatalogSearchService.SearchEntitlements
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/c1.api.requestcatalog.v2.SearchEntitlementsRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.requestcatalog.v2.SearchEntitlementsResponse'
          description: Successful response
  /api/v1/user/get/{id}:
    get:
      description: Invokes the c1.api.user.v1.UserService.Get method.
      operationId: c1.api.user.v1.UserService.Get
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          description: The id field.
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.user.v1.UserServiceGetResponse'
          description: Successful response
components:
  schemas:
    c1.api.app.v1.AppEntitlement:
      description: |
        The AppEntitlement message.

        This message contains a oneof named max_grant_duration. Only a single field of the following list may be set at a time:
          - durationUnset
          - durationGrant
      properties:
        alias:
          description: The alias field.
        appId:
          description: The appId field.
        appResourceId:
          description: The appResourceId field.
        appResourceTypeId:
          description: The appResourceTypeId field.
        certifyPolicyId:
          description: The certifyPolicyId field.
        complianceFrameworkValueIds:
          description: The complianceFrameworkValueIds field.
          items: {}
          nullable: true
        createdAt:
          format: date-time
        deletedAt:
          format: date-time
        description:
          description: The description field.
        displayName:
          description: The displayName field.
        durationGrant:
          format: duration
        durationUnset:
          nullable: true
        grantCount:
          description: The grantCount field.
          format: int64
        grantPolicyId:
          description: The grantPolicyId field.
        id:
          description: The id field.
        provisionerPolicy:
          $ref: '#/components/schemas/c1.api.policy.v1.ProvisionPolicy'
        revokePolicyId:
          description: The revokePolicyId field.
        riskLevelValueId:
          description: The riskLevelValueId field.
        slug:
          description: The slug field.
        systemBuiltin:
          description: The systemBuiltin field.
        updatedAt:
          format: date-time
    c1.api.app.v1.AppResource:
      description: The AppResource message.
      example:
        createdAt: ""
        deletedAt: ""
        customDescription: ""
        displayName: ""
        appId: ""
        grantCount: ""
        description: ""
        id: ""
        appResourceTypeId: ""
        updatedAt: ""
      properties:
        appId:
          description: The appId field.
        appResourceTypeId:
          description: The appResourceTypeId field.
        createdAt:
          format: date-time
        customDescription:
          description: The customDescription field.
        deletedAt:
          format: date-time
        description:
          description: The description field.
        displayName:
          description: The displayName field.
        grantCount:
          description: The grantCount field.
          format: int64
        id:
          description: The id field.
        updatedAt:
          format: date-time
    c1.api.app.v1.AppResourceServiceGetResponse:
      description: The AppResourceServiceGetResponse message.
      example:
        expanded: ""
        appResourceView:
          appResource:
            createdAt: ""
            deletedAt: ""
            customDescription: ""
            displayName: ""
            appId: ""
            grantCount: ""
            description: ""
            id: ""
            appResourceTypeId: ""
            updatedAt: ""
          resourceTypePath: ""
          appPath: ""
      properties:
        appResourceView:
          $ref: '#/components/schemas/c1.api.app.v1.AppResourceView'
        expanded:
          description: The expanded field.
          items:
            additionalProperties: {}
            description: Contains an arbitrary serialized message along with a @type
              that describes the type of the serialized message.
            properties:
              '@type':
                description: The type of the serialized message.
          nullable: true
    c1.api.app.v1.AppResourceType:
      description: The AppResourceType message.
      example:
        createdAt: ""
        deletedAt: ""
        displayName: ""
        appId: ""
        id: ""
        updatedAt: ""
      properties:
        appId:
          description: The appId field.
        createdAt:
          format: date-time
        deletedAt:
          format: date-time
        displayName:
          description: The displayName field.
        id:
          description: The id field.
        updatedAt:
          format: date-time
    c1.api.app.v1.AppResourceTypeServiceGetResponse:
      description: The AppResourceTypeServiceGetResponse message.
      example:
        expanded: ""
        appResourceTypeView:
          appResourceType:
            createdAt: ""
            deletedAt: ""
            displayName: ""
            appId: ""
            id: ""
            updatedAt: ""
          appPath: ""
      properties:
        appResourceTypeView:
          $ref: '#/components/schemas/c1.api.app.v1.AppResourceTypeView'
        expanded:
          description: The expanded field.
          items:
            additionalProperties: {}
            description: Contains an arbitrary serialized message along with a @type
              that describes the type of the serialized message.
            properties:
              '@type':
                description: The type of the serialized message.
          nullable: true
    c1.api.app.v1.AppResourceTypeView:
      description: The AppResourceTypeView message.
      example:
        appResourceType:
          createdAt: ""
          deletedAt: ""
          displayName: ""
          appId: ""
          id: ""
          updatedAt: ""
        appPath: ""
      properties:
        appPath:
          description: The appPath field.
        appResourceType:
          $ref: '#/components/schemas/c1.api.app.v1.AppResourceType'
    c1.api.app.v1.AppResourceView:
      description: The AppResourceView message.
      example:
        appResource:
          createdAt: ""
          deletedAt: ""
          customDescription: ""
          displayName: ""
          appId: ""
          grantCount: ""
          description: ""
          id: ""
          appResourceTypeId: ""
          updatedAt: ""
        resourceTypePath: ""
        appPath: ""
      properties:
        appPath:
          description: The appPath field.
        appResource:
          $ref: '#/components/schemas/c1.api.app.v1.AppResource'
        resourceTypePath:
          description: The resourceTypePath field.
    c1.api.auth.v1.IntrospectResponse:
      description: The IntrospectResponse message.
      example:
        accessTokenId: ""
        features: ""
        permissions: ""
        roles: ""
        tenantId: ""
        userId: ""
        principleId: ""
      properties:
        accessTokenId:
          description: The accessTokenId field.
        features:
          description: The features field.
          items: {}
          nullable: true
        permissions:
          description: The permissions field.
          items: {}
          nullable: true
        principleId:
          description: The principleId field.
        roles:
          description: The roles field.
          items: {}
          nullable: true
        tenantId:
          description: The tenantId field.
        userId:
          description: The userId field.
    c1.api.policy.v1.ConnectorProvision:
      description: The ConnectorProvision message.
      nullable: true
    c1.api.policy.v1.DelegatedProvision:
      description: The DelegatedProvision message.
      properties:
        appId:
          description: The appId field.
        entitlementId:
          description: The entitlementId field.
      nullable: true
    c1.api.policy.v1.ManualProvision:
      description: The ManualProvision message.
      properties:
        instructions:
          description: The instructions field.
        userIds:
          description: The userIds field.
          items: {}
          nullable: true
      nullable: true
    c1.api.policy.v1.ProvisionPolicy:
      description: |
        The ProvisionPolicy message.

        This message contains a oneof named typ. Only a single field of the following list may be set at a time:
          - connector
          - manual
          - delegated
      properties:
        connector:
          description: The ConnectorProvision message.
          nullable: true
        delegated:
          $ref: '#/components/schemas/c1.api.policy.v1.DelegatedProvision'
        manual:
          $ref: '#/components/schemas/c1.api.policy.v1.ManualProvision'
    c1.api.requestcatalog.v2.SearchEntitlementsRequest:
      description: The SearchEntitlementsRequest message.
      properties:
        entitlementAlias:
          description: The entitlementAlias field.
        pageSize:
          description: The pageSize field.
          format: int32
        pageToken:
          description: The pageToken field.
        query:
          description: The query field.
    c1.api.requestcatalog.v2.SearchEntitlementsResponse:
      description: The SearchEntitlementsResponse message.
      example:
        nextPageToken: ""
        list: ""
      properties:
        list:
          description: The list field.
          items:
            $ref: '#/components/schemas/c1.api.app.v1.AppEntitlement'
          nullable: true
        nextPageToken:
          description: The nextPageToken field.
    c1.api.user.v1.User:
      description: The User message.
      example:
        employmentStatusSources: ""
        directoryStatusSources: ""
        departmentSources: ""
        employmentType: ""
        delegatedUserId: ""
        displayName: ""
        jobTitle: ""
        jobTitleSources: ""
        employmentStatus: ""
        createdAt: ""
        deletedAt: ""
        managerIds: ""
        managerSources: ""
        roleIds: ""
        directoryStatus: ""
        employmentTypeSources: ""
        id: ""
        department: ""
        directoryIds: ""
        email: ""
        status: ""
        updatedAt: ""
      properties:
        createdAt:
          format: date-time
        delegatedUserId:
          description: The delegatedUserId field.
        deletedAt:
          format: date-time
        department:
          description: The department field.
        departmentSources:
          description: The departmentSources field.
          items:
            $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
          nullable: true
        directoryIds:
          description: The directoryIds field.
          items: {}
          nullable: true
        directoryStatus:
          description: The directoryStatus field.
          enum:
          - UNKNOWN
          - ENABLED
          - DISABLED
          - DELETED
        directoryStatusSources:
          description: The directoryStatusSources field.
          items:
            $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
          nullable: true
        displayName:
          description: The displayName field.
        email:
          description: The email field.
        employmentStatus:
          description: The employmentStatus field.
        employmentStatusSources:
          description: The employmentStatusSources field.
          items:
            $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
          nullable: true
        employmentType:
          description: The employmentType field.
        employmentTypeSources:
          description: The employmentTypeSources field.
          items:
            $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
          nullable: true
        id:
          description: The id field.
        jobTitle:
          description: The jobTitle field.
        jobTitleSources:
          description: The jobTitleSources field.
          items:
            $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
          nullable: true
        managerIds:
          description: The managerIds field.
          items: {}
          nullable: true
        managerSources:
          description: The managerSources field.
          items:
            $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
          nullable: true
        roleIds:
          description: The roleIds field.
          items: {}
          nullable: true
        status:
          description: The status field.
          enum:
          - UNKNOWN
          - ENABLED
          - DISABLED
          - DELETED
        updatedAt:
          format: date-time
    c1.api.user.v1.UserAttributeMappingSource:
      description: The UserAttributeMappingSource message.
      properties:
        appId:
          description: The appId field.
        appUserId:
          description: The appUserId field.
        appUserProfileAttributeKey:
          description: The appUserProfileAttributeKey field.
        userAttributeMappingId:
          description: The userAttributeMappingId field.
        value:
          description: The value field.
    c1.api.user.v1.UserServiceGetResponse:
      description: The UserServiceGetResponse message.
      example:
        expanded: ""
        userView:
          managersPath: ""
          rolesPath: ""
          delegatedUserPath: ""
          directoriesPath: ""
          user:
            employmentStatusSources: ""
            directoryStatusSources: ""
            departmentSources: ""
            employmentType: ""
            delegatedUserId: ""
            displayName: ""
            jobTitle: ""
            jobTitleSources: ""
            employmentStatus: ""
            createdAt: ""
            deletedAt: ""
            managerIds: ""
            managerSources: ""
            roleIds: ""
            directoryStatus: ""
            employmentTypeSources: ""
            id: ""
            department: ""
            directoryIds: ""
            email: ""
            status: ""
            updatedAt: ""
      properties:
        expanded:
          description: The expanded field.
          items:
            additionalProperties: {}
            description: Contains an arbitrary serialized message along with a @type
              that describes the type of the serialized message.
            properties:
              '@type':
                description: The type of the serialized message.
          nullable: true
        userView:
          $ref: '#/components/schemas/c1.api.user.v1.UserView'
    c1.api.user.v1.UserView:
      description: The UserView message.
      example:
        managersPath: ""
        rolesPath: ""
        delegatedUserPath: ""
        directoriesPath: ""
        user:
          employmentStatusSources: ""
          directoryStatusSources: ""
          departmentSources: ""
          employmentType: ""
          delegatedUserId: ""
          displayName: ""
          jobTitle: ""
          jobTitleSources: ""
          employmentStatus: ""
          createdAt: ""
          deletedAt: ""
          managerIds: ""
          managerSources: ""
          roleIds: ""
          directoryStatus: ""
          employmentTypeSources: ""
          id: ""
          department: ""
          directoryIds: ""
          email: ""
          status: ""
          updatedAt: ""
      properties:
        delegatedUserPath:
          description: The delegatedUserPath field.
        directoriesPath:
          description: The directoriesPath field.
        managersPath:
          description: The managersPath field.
        rolesPath:
          description: The rolesPath field.
        user:
          $ref: '#/components/schemas/c1.api.user.v1.User'
